### ISSUE TITLE
Lab1 Does Ingress Does Not Work With Later Versions of K8s

### ISSUE THREAD

**Issue by NiallJude** [phcollignon/helm3#30]
Starting in version `1.19`, K8s dropped support for `extenstions/v1beta1` Ingress and now, you must use `networking.k8s.io/v1` but there are also some changes to fields + variables which are necessary to update the ingress.yaml. Do you have a version available which is compatible? I would prefer not to rollback my k8s version.

Error:

> kubectl apply -f ../../lab1_kubectl_version1/yaml/ingress.yaml
error: unable to recognize "../../lab1_kubectl_version1/yaml/ingress.yaml": no matches for kind "Ingress" in version "extensions/v1beta1"

I think it's something like this now but it's not exactly correct:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
spec:
  rules:
  - host: frontend.minikube.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 80
  - host: backend.minikube.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backend
            port:
              number: 80
```
